import { DEMO_IDS } from '@/lib/ids'
import type { Family, FamilyMember, FamilyMembership, FixedDeposit } from '@/lib/types'

export const demoFamilies: Family[] = [
  { id: DEMO_IDS.mulgundFamily, name: 'Mulgund family' },
  { id: DEMO_IDS.otherFamily, name: 'Other family' },
]

export const demoMemberships: FamilyMembership[] = [
  {
    family_id: DEMO_IDS.mulgundFamily,
    user_id: DEMO_IDS.vikram,
    role: 'family_admin',
  },
  {
    family_id: DEMO_IDS.otherFamily,
    user_id: DEMO_IDS.other,
    role: 'family_admin',
  },
]

export const demoMembers: FamilyMember[] = [
  {
    id: DEMO_IDS.vikramMember,
    family_id: DEMO_IDS.mulgundFamily,
    full_name: 'Vikram A Mulgund',
    display_name: 'Vikram',
    linked_user_id: DEMO_IDS.vikram,
    bank_customer_id: '1700',
    notes: null,
  },
  {
    id: DEMO_IDS.otherMember,
    family_id: DEMO_IDS.otherFamily,
    full_name: 'Other Holder',
    display_name: null,
    linked_user_id: DEMO_IDS.other,
    bank_customer_id: '9999',
    notes: null,
  },
]

export const demoDeposits: FixedDeposit[] = [
  {
    id: DEMO_IDS.fd40599,
    family_id: DEMO_IDS.mulgundFamily,
    family_member_id: DEMO_IDS.vikramMember,
    fd_account_no: '01FD40599',
    bank_customer_id: '1700',
    holder_name: 'VIKRAM A MULGUND',
    holder_address: 'Mulgund Complex, Gadag',
    principal_amount: 150000,
    principal_amount_words: 'One Lakh Fifty Thousand only',
    interest_rate_pct: 11,
    tenure_years: 3,
    tenure_months: 0,
    tenure_days: 0,
    tenure_label: '3 Years',
    interest_mode: 'monthly',
    monthly_interest_amount: 1375,
    interest_credit_account: '01003MS001396',
    maturity_value: 150000,
    fd_date: '2025-05-26',
    transaction_date: '2025-05-26',
    print_at: null,
    maturity_date: '2028-05-25',
    nominee_name: 'AMRUTMATI VIKRAM MULGUND',
    nominee_relationship: 'wife',
    status: 'active',
    notes: null,
  },
  {
    id: DEMO_IDS.fd32450,
    family_id: DEMO_IDS.mulgundFamily,
    family_member_id: DEMO_IDS.vikramMember,
    fd_account_no: '01FD32450',
    bank_customer_id: '1700',
    holder_name: 'VIKRAM A MULGUND',
    holder_address: 'Mulgund Complex, Gadag',
    principal_amount: 450000,
    principal_amount_words: 'Four Lakh Fifty Thousand only',
    interest_rate_pct: 11,
    tenure_years: 5,
    tenure_months: 0,
    tenure_days: 0,
    tenure_label: '5 Years',
    interest_mode: 'on_maturity',
    monthly_interest_amount: null,
    interest_credit_account: null,
    maturity_value: 697500,
    fd_date: '2023-10-25',
    transaction_date: '2023-10-25',
    print_at: null,
    maturity_date: '2028-10-23',
    nominee_name: 'SHAKUNTALA A MULGUND',
    nominee_relationship: 'Mother',
    status: 'active',
    notes: null,
  },
  {
    id: DEMO_IDS.otherFd,
    family_id: DEMO_IDS.otherFamily,
    family_member_id: DEMO_IDS.otherMember,
    fd_account_no: '01FD00001',
    bank_customer_id: '9999',
    holder_name: 'OTHER HOLDER',
    holder_address: null,
    principal_amount: 100000,
    principal_amount_words: null,
    interest_rate_pct: 10,
    tenure_years: 1,
    tenure_months: 0,
    tenure_days: 0,
    tenure_label: '1 Year',
    interest_mode: 'monthly',
    monthly_interest_amount: 833.33,
    interest_credit_account: null,
    maturity_value: 100000,
    fd_date: '2026-01-01',
    transaction_date: null,
    print_at: null,
    maturity_date: '2027-01-01',
    nominee_name: null,
    nominee_relationship: null,
    status: 'active',
    notes: null,
  },
]
